### ISSUE TITLE
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by vitulgoyani** [GeekyAnts/flick-video-player#279]
E/ExoPlayerImplInternal(21517): Playback error
E/ExoPlayerImplInternal(21517):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
E/ExoPlayerImplInternal(21517):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(21517):       at android.os.Looper.loopOnce(Looper.java:205)
E/ExoPlayerImplInternal(21517):       at android.os.Looper.loop(Looper.java:294)
E/ExoPlayerImplInternal(21517):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21517):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(21517):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ExoPlayerImplInternal(21517):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ExoPlayerImplInternal(21517):       at java.lang.Thread.run(Thread.java:1012)
E/ExoPlayerImplInternal(21517):   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal(21517):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:653)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal(21517):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:376)
E/ExoPlayerImplInternal(21517):       ... 7 more
E/ExoPlayerImplInternal(21517):   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
E/ExoPlayerImplInternal(21517):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal(21517):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:260)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal(21517):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal(21517):       ... 29 more
E/ExoPlayerImplInternal(21517):   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(21517):       ... 42 more

**Comment by vitulgoyani** [comment]
is there any way to bypass this error?

**Comment by perzend** [comment]
Have you solved the problem?
I get the same error when I try to play a link to a video and use a self-signed certificate. Any ideas?
