### ISSUE TITLE
Android M3U8 video format not playing

### ISSUE THREAD

**Issue by JasurbekCoder01** [GeekyAnts/flick-video-player#280]
<img width="1370" alt="Screenshot 2024-06-27 at 17 09 05" src="https://github.com/GeekyAnts/flick-video-player/assets/94785634/48f11d62-0d45-4eb8-8356-b45883e04729">

E/ExoPlayerImplInternal(13070): Playback error
E/ExoPlayerImplInternal(13070):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
E/ExoPlayerImplInternal(13070):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(13070):       at android.os.Looper.loopOnce(Looper.java:211)
E/ExoPlayerImplInternal(13070):       at android.os.Looper.loop(Looper.java:300)
E/ExoPlayerImplInternal(13070):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(13070):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
E/ExoPlayerImplInternal(13070):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(13070):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ExoPlayerImplInternal(13070):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ExoPlayerImplInternal(13070):       at java.lang.Thread.run(Thread.java:1012)
I/ExoPlayerImpl(13070): Release f9331cb [ExoPlayerLib/2.18.7] [sweet, 2209116AG, Xiaomi, 33] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.hls, goog.exo.datasource]

why not playing video in android?

**Comment by geekruchika** [comment]
Can you please share more versions details?
