### ISSUE TITLE
How to use with Image_picker Package?

### ISSUE THREAD

**Issue by hectorAguero** [GeekyAnts/flick-video-player#37]
### What's the issue?

So, I'm using **image_picker package** to pick a video file, and show with **video_player package**, based on the example code of image_picker repo 

I see the different examples of Flick Video Player, and I'm achieve to show custom controls, but I have different errors in the log for the code in initState or in Dispose.

### Sample Code

The example file of the next link has a class **AspectRatioVideo** at the end, and I put the Flick Video Player code inside in the lines with the comment `//Flick Video Player Code` 

https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/example/lib/main.dart

You can download the image picker example  folder with downgit, add the Flick Video Player package and change the next class.

****
```dart
class AspectRatioVideo extends StatefulWidget {
  AspectRatioVideo(this.controller);

  final VideoPlayerController controller;

  @override
  AspectRatioVideoState createState() => AspectRatioVideoState();
}

class AspectRatioVideoState extends State<AspectRatioVideo> {
  VideoPlayerController get controller => widget.controller;
  bool initialized = false;
  FlickManager flickManager; //Flick Video Player Code

  void _onVideoControllerUpdate() {
    if (!mounted) {
      flickManager.dispose(); //Flick Video Player code
      return;
    }
    if (initialized != controller.value.initialized) {
      flickManager = FlickManager(videoPlayerController: widget.controller);  //Flick Video Player Code
      initialized = controller.value.initialized;
      setState(() {});
    }
  }

  @override
  void initState() {
    super.initState();
    controller.addListener(_onVideoControllerUpdate);
  }

  @override
  void dispose() {
    controller.removeListener(_onVideoControllerUpdate);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (initialized) {
      return Center(
        child: AspectRatio(
          aspectRatio: controller.value?.aspectRatio,
          child: FlickVideoPlayer(flickManager: flickManager) //Flick Video Player code
        ),
      );
    } else {
      return Container();
    }
  }
}
````
****
### Error Lines in log
This one happens when I open the page.
`The line with the #5  refers to _onVideoControllerUpdate of the previous class.`
```
E/flutter ( 4337): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null.
E/flutter ( 4337): Receiver: null
E/flutter ( 4337): Tried calling: dependOnInheritedWidgetOfExactType<_ModalScopeStatus>()
E/flutter ( 4337): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4337): #1      ModalRoute.of package:flutter/…/widgets/routes.dart:882
E/flutter ( 4337): #2      FlickVideoManager._changeVideo package:flick_video_player/…/manager/video_manager.dart:144
E/flutter ( 4337): #3      FlickVideoManager._handleChangeVideo package:flick_video_player/…/manager/video_manager.dart:104
E/flutter ( 4337): #4      new FlickManager package:flick_video_player/…/manager/flick_manager.dart:35
E/flutter ( 4337): #5      AspectRatioVideoState._onVideoControllerUpdate  my_project/page_video.dart:287
E/flutter ( 4337): #6      ChangeNotifier.notifyListeners package:flutter/…/foundation/change_notifier.dart:209
E/flutter ( 4337): #7      ValueNotifier.value= package:flutter/…/foundation/change_notifier.dart:276
E/flutter ( 4337): #8      VideoPlayerController.initialize.eventListener  package:video_player/video_player.dart:286
E/flutter ( 4337): #9      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter ( 4337): #10     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
```

**Comment by geekruchika** [comment]
Please try with the latest version and open this issue if still persist.
Thanks.
