### ISSUE TITLE
Videos Not Displaying Thumbnails But A Black Screen

### ISSUE THREAD

**Issue by RalphMarvin** [GeekyAnts/flick-video-player#87]
Sometimes my flick video shows up like in the image below:

![image](https://user-images.githubusercontent.com/15852456/117441217-91849200-af24-11eb-87a5-0006ecb7b7e7.png)

And this is the error I get:

```
E/ExoPlayerImplInternal( 9171): Playback error
E/ExoPlayerImplInternal( 9171):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9171):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal( 9171):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 9171):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal( 9171):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9171):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
E/ExoPlayerImplInternal( 9171):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:383)
E/ExoPlayerImplInternal( 9171):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 9171):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
E/ExoPlayerImplInternal( 9171):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 9171):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 9171):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 9171):       at java.lang.Thread.run(Thread.java:919)
```

**Comment by geekruchika** [comment]
Feel free to reopen if required.
