### ISSUE TITLE
NullPointerException for video_player on release mode

### ISSUE THREAD

**Issue by husen-hn** [GeekyAnts/flick-video-player#88]
```dart
Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (14037): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
E/flutter (14037): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null)
E/flutter (14037): #0      VideoPlayerApi.seekTo (package:video_player_platform_interface/messages.dart:365)
E/flutter (14037): <asynchronous suspension>
E/flutter (14037): #1      VideoPlayerController.seekTo (package:video_player/video_player.dart:494)
E/flutter (14037): <asynchronous suspension>
E/flutter (14037): 
I/flutter (14037): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (14037): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by callmejm** [comment]
> Soon we will release updates with a fix for it.

I using `0.4.0-dev.3` still facing this issue
