### ISSUE TITLE
Error: Unexpected null value.

### ISSUE THREAD

**Issue by bholendraofficial** [GeekyAnts/flick-video-player#98]
Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:57795/dart_sdk.js:5348:11)
    at Object.nullCheck (http://localhost:57795/dart_sdk.js:5681:30)
    at video_player_web.VideoPlayerPlugin.new.seekTo (http://localhost:57795/packages/video_player_web/video_player_web.dart.lib.js:240:21)
    at seekTo.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at video_player_web.VideoPlayerPlugin.new.seekTo (http://localhost:57795/packages/video_player_web/video_player_web.dart.lib.js:239:20)
    at video_player.VideoPlayerController.asset.seekTo (http://localhost:57795/packages/video_player/video_player.dart.lib.js:1210:49)
    at seekTo.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at video_player.VideoPlayerController.asset.seekTo (http://localhost:57795/packages/video_player/video_player.dart.lib.js:1201:20)
    at flick_manager.FlickControlManager.new.seekTo (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:470:60)
    at seekTo.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at flick_manager.FlickControlManager.new.seekTo (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:469:20)
    at flick_manager.FlickControlManager.new.replay (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:430:12)
    at http://localhost:57795/packages/connect/ui/activity/OtpVerificationScreen.dart.lib.js:1462:51
    at Object._checkAndCall (http://localhost:57795/dart_sdk.js:5558:16)
    at Object.dcall (http://localhost:57795/dart_sdk.js:5563:17)
    at flick_manager.FlickManager.new.[_handleVideoEnd] (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:86:14)
    at flick_manager.FlickVideoManager.new.handleVideoEnd (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:312:43)
    at flick_manager.FlickVideoManager.new.[_videoListener] (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:298:16)
    at video_player.VideoPlayerController.asset.notifyListeners (http://localhost:57795/packages/flutter/src/foundation/change_notifier.dart.lib.js:108:41)
    at video_player.VideoPlayerController.asset.set value [as value] (http://localhost:57795/packages/flutter/src/foundation/change_notifier.dart.lib.js:198:14)
    at video_player.VideoPlayerController.asset.setVolume (http://localhost:57795/packages/video_player/video_player.dart.lib.js:1217:20)
    at setVolume.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at video_player.VideoPlayerController.asset.setVolume (http://localhost:57795/packages/video_player/video_player.dart.lib.js:1216:20)
    at flick_manager.FlickControlManager.new.setVolume (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:508:74)
    at setVolume.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at flick_manager.FlickControlManager.new.setVolume (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:506:20)
    at flick_manager.FlickControlManager.new.mute (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:490:20)
    at mute.next (<anonymous>)
    at runBody (http://localhost:57795/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:57795/dart_sdk.js:39281:7)
    at flick_manager.FlickControlManager.new.mute (http://localhost:57795/packages/flick_video_player/src/manager/flick_manager.dart.lib.js:488:20)
    at OtpVerificationScreen._OtpVerificationScreenState.new.initState (http://localhost:57795/packages/connect/ui/activity/OtpVerificationScreen.dart.lib.js:1464:47)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53342:54)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatelessElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatelessElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatelessElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatelessElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at _InheritedNotifierElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at _InheritedNotifierElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at _InheritedNotifierElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at _InheritedNotifierElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at _InheritedNotifierElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at _InheritedNotifierElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.InheritedElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.InheritedElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.InheritedElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.InheritedElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatelessElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatelessElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatelessElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatelessElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatelessElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatelessElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatelessElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatelessElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at basic._OffstageElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at basic._OffstageElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at basic._OffstageElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at framework.InheritedElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.InheritedElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.InheritedElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.InheritedElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46145:31)
    at framework.InheritedElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.InheritedElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatelessElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatelessElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatelessElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatelessElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at framework.StatefulElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30233:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53361:29)
    at framework.StatefulElement.new.mount (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30229:28)
    at overlay$._TheatreElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28991:16)
    at overlay$._TheatreElement.new.inflateWidget (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:32152:28)
    at overlay$._TheatreElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28845:25)
    at overlay$._TheatreElement.new.updateChildren (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29659:44)
    at overlay$._TheatreElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:32172:36)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53390:12)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30332:12)
    at _InheritedNotifierElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at _InheritedNotifierElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at _InheritedNotifierElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at _InheritedNotifierElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30332:12)
    at _InheritedNotifierElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:50703:15)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.SingleChildRenderObjectElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46152:31)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.StatefulElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53390:12)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.SingleChildRenderObjectElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46152:31)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.SingleChildRenderObjectElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:46152:31)
    at framework.InheritedElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.InheritedElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.InheritedElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.InheritedElement.new.update (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30332:12)
    at framework.StatefulElement.new.updateChild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:28832:17)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:30265:33)
    at framework.StatefulElement.new.performRebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:53368:13)
    at framework.StatefulElement.new.rebuild (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:29337:12)
    at framework.BuildOwner.new.buildScope (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:52812:55)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:57795/packages/flutter/src/widgets/widget_span.dart.lib.js:55572:77)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:57795/packages/flutter/src/rendering/layer.dart.lib.js:5413:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:57795/packages/flutter/src/scheduler/binding.dart.lib.js:767:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:57795/packages/flutter/src/scheduler/binding.dart.lib.js:735:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:57795/packages/flutter/src/scheduler/binding.dart.lib.js:690:12)
    at Object.invoke (http://localhost:57795/dart_sdk.js:186344:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:57795/dart_sdk.js:166270:15)
    at http://localhost:57795/dart_sdk.js:183433:55

**Comment by geekruchika** [comment]
Resolved in 0.4.0-dev.2.
